Add TS type definition for hbs import
ember-template-imports/ember-template-imports pull request #18
Opened 2021-03-27 18:17 UTC by josemarluedke

Adds simple type definition for the hbs import `import { hbs } from 'ember-template-imports';`.

Helps with #14.

2021-09-03 19:04 UTC, chriskrycho approved these changes
👍🏼 to this as a good stopgap here.

2022-05-18 12:57 UTC, chriskrycho requested changes

2022-05-18 12:57 UTC, chriskrycho commented on index.d.ts
> +export function hbs(tagged: TemplateStringsArray): TemplateFactory;
Hmm. The `TemplateFactory` definition here won't actually *do* anything; it's just an empty interface. We need to do one of:

- importing the *actual* type from Ember's types and using that so we can guarantee interop (recommended)
- making it return `unknown`, which will require casts for folks to use it (not recommended)

2022-11-11 03:28 UTC, chriskrycho commented
As we start to move toward stabilizing `<template>`, I'm doing some cleanup—I welcome input from @dfreeman and @jamescdavis here on the TS front, and from other folks on Framework on the more general front:

My *very* strong intuition here is that we should *not* ship a specific type for this `hbs`, and indeed move to *deprecate* it.

2022-11-11 11:39 UTC, dfreeman commented
If you're using Glint with `ember-template-imports` today, I believe we provide a declaration for `hbs` there (and if you're _not_ using Glint, you're going to get a bunch of spurious "unused symbol" errors from vanilla TS).

As we move toward our next breaking release of Glint, though, I'm inclined to agree with @chriskrycho and say we should probably drop that and discourage the use of `hbs` since `<template>` has been officially adopted as the path forward.

2022-11-11 20:02 UTC, closed without merging